# Generated by Django 6.0.1 on 2026-01-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(unique=True)),
                ('holiday_name', models.CharField(max_length=100)),
                ('holiday_type', models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional'), ('Weekend', 'Weekend')], max_length=20)),
            ],
        ),
    ]
