# Generated by Django 6.0.1 on 2026-01-21 03:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits', regex='^\\d{10}$')])),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HR', 'HR'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=20)),
                ('pan_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('uan_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='UAN must be exactly 12 digits', regex='^\\d{12}$')])),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code format', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reports', to='accounts.employee')),
                ('pa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_reports', to='accounts.employee')),
                ('sa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_reports', to='accounts.employee')),
            ],
        ),
    ]
