# Generated by Django 6.0.1 on 2026-01-21 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('salary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conveyance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('epf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('payslip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conveyance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('epf_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lop_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
