# Generated by Django 6.0.1 on 2026-01-21 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_name', models.CharField(max_length=20, unique=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('max_per_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('is_auto_converted', models.BooleanField(default=False)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approver_role', models.CharField(choices=[('RM1', 'Primary Manager'), ('RM2', 'Secondary Manager'), ('HR', 'HR')], max_length=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leaveapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('balance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('cl_balance', models.PositiveIntegerField(default=18)),
                ('ml_balance', models.PositiveIntegerField(default=6)),
                ('ol_balance', models.PositiveIntegerField(default=3)),
                ('lop_taken', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
