# Generated by Django 6.0.1 on 2026-01-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_user'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveapproval',
            unique_together={('leave', 'approver')},
        ),
    ]
