# Generated by Django 6.0.1 on 2026-01-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaveapproval_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapproval',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave.leaveapplication'),
        ),
    ]
