# Generated by Django 6.0.1 on 2026-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leaveapproval_leave'),
    ]

    operations = [
        #migrations.AddField(
         #   model_name='leavetype',
          #  name='code',
           # field=models.CharField(default='TEMP', help_text='CL / ML / OL / LOP', max_length=5, unique=True),
            #preserve_default=False,
        #),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(max_length=50),
        ),
    ]
