# Generated by Django 6.0.1 on 2026-02-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoff', '0002_remove_compoff_expiry_date_compoff_created_at_and_more'),
        ('leave', '0004_leavetype_code_alter_leavetype_leave_name'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='leaveapproval',
            name='compoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='compoff.compoff'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
