# Generated by Django 6.0.1 on 2026-02-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_leavetype_code_leaveapproval_compoff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapproval',
            name='compoff',
        ),
    ]
