# Generated by Django 6.0.1 on 2026-02-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_remove_leaveapproval_compoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='compoff_credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
