# Generated by Django 6.0.1 on 2026-02-26 09:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_alter_leaveapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='cl_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='compoff_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='lop_taken',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='ml_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='ol_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
    ]
