# Generated by Django 6.0.1 on 2026-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_alter_leavebalance_cl_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
