# Generated by Django 6.0.1 on 2026-03-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_alter_leaveapplication_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapproval',
            options={'ordering': ['approval_id']},
        ),
    ]
