# Generated by Django 6.0.1 on 2026-03-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_user'),
        ('leave', '0011_alter_leaveapproval_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_leaves', to='accounts.employee'),
        ),
    ]
