# Generated by Django 6.0.1 on 2026-01-21 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOff',
            fields=[
                ('compoff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('hours_worked', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('is_used', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('used_for_leave', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leaveapplication')),
            ],
        ),
    ]
