# Generated by Django 6.0.1 on 2026-02-03 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoff',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='compoff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compoff',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='compoff',
            name='year',
            field=models.PositiveIntegerField(default=2026),
            preserve_default=False,
        ),
    ]
