# Generated by Django 6.0.1 on 2026-02-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compoff', '0002_remove_compoff_expiry_date_compoff_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoff',
            name='used_for_leave',
        ),
    ]
