# Generated by Django 6.0.1 on 2026-02-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_user'),
        ('compoff', '0003_remove_compoff_used_for_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffApproval',
            fields=[
                ('approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('RM', 'Reporting Manager'), ('HR', 'HR')], max_length=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('compoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='compoff.compoff')),
            ],
            options={
                'unique_together': {('compoff', 'approver')},
            },
        ),
    ]
