# Generated by Django 6.0.1 on 2026-02-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoff', '0004_compoffapproval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compoffapproval',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='compoffapproval',
            name='approver_role',
            field=models.CharField(choices=[('RM1', 'Rm1'), ('RM2', 'Rm2'), ('HR', 'Hr')], default='HR', max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='compoffapproval',
            name='role',
        ),
    ]
