# Generated by Django 6.0.1 on 2026-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoff', '0005_alter_compoffapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoff',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='compoffapproval',
            name='approver_role',
            field=models.CharField(choices=[('RM1', 'Rm1'), ('RM2', 'Rm2'), ('HR', 'Hr')], default='RM1', max_length=10),
        ),
        migrations.AlterField(
            model_name='compoffapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
